variables:
  - name: rgName
    value: cc-rg-demo-config-$(environmentName)
  - name: rgLocation
    value: Australia Southeast
  - name: planName
    value: plan-config-$(environmentName)
  - name: planSku
    value: S1
  - name: planCapacity
    value: 1
  - name: appInsightsName
    value: ins-config-demo-$(environmentName)
  - name: sgName
    value: ccsgconfigdemo$(environmentName)
  - name: azConfigName
    value: appcs-custapi-$(environmentName)