parameters:
  - name: buildNumber
    type: string

steps:

  - task: AzureCLI@2    
    displayName: "Create resource group"
    inputs:
      azureSubscription: "$(azureSubscription)"
      scriptType: "pscore"
      scriptLocation: "inlineScript"
      inlineScript: |
        $ifExists = az group exists -n "$(rgName)"
        if ($ifExists -eq 'false') {
          echo 'creating the resource group'
          az group create -n "$(rgName)" -l "$(rgLocation)"
        }

  - task: AzureCLI@2    
    displayName: "Provision resources"
    inputs:
      azureSubscription: "$(azureSubscription)"
      scriptType: "pscore"
      scriptLocation: "inlineScript"
      inlineScript: |    
        az deployment group create `
        --name ccazconfigdemo `
        --resource-group "$(rgName)" `
        --template-file "$(Pipeline.Workspace)/deploy/main.bicep" `
        --parameters "buildNumber=$(Build.BuildNumber)" `
        "location=$(rgLocation)" `
        "planCapacity=$(planCapacity)" `
        "planName=$(planName)" `
        "planSku=$(planSku)" `
        "appInsightsName=$(appInsightsName)" `
        "sgName=$(sgName)" `
        "azConfigName=$(azConfigName)" `
        "apiEnvironment=$(apiEnvironment)" `
        "keyVaultName=$(keyVaultName)" `
        "apiName=$(apiName)"