parameters:
  - name: buildNumber
    type: string

steps:

  - task: AzureCLI@2    
    displayName: "Create resource group"
    inputs:
      azureSubscription: "$(azureSubscription)"
      scriptType: "pscore"
      scriptLocation: "inlineScript"
      inlineScript: |
        $ifExists = az group exists -n "$(rgName)"
        if ($ifExists -eq 'false') {
          echo 'creating the resource group'
          az group create -n "$(rgName)" -l "$(rgLocation)"
        }

  - task: AzureCLI@2    
    displayName: "Provision resources"
    inputs:
      azureSubscription: "$(azureSubscription)"
      scriptType: "pscore"
      scriptLocation: "inlineScript"
      inlineScript: |    
        az deployment group create `
        --name ccazconfigdemo-$(Build.BuildNumber) `
        --resource-group "$(rgName)" `
        --template-file "$(Pipeline.Workspace)/deploy/main.bicep" `
        --parameters "buildNumber=$(Build.BuildNumber)" `
        "rgName=$(rgName)" `
        "location=$(rgLocation)" `
        "planCapacity=$(planCapacity)" `
        "planName=$(planName)" `
        "planSku=$(planSku)" `
        "appInsightsName=$(appInsightsName)" `
        "sgName=$(sgName)" `
        "azConfigName=$(azConfigName)" `
        "commonRgName=$(commonRgName)" `
        "commonAzConfigName=$(commonAzConfigName)" `
        "apiEnvironment=$(apiEnvironment)" `
        "keyVaultName=$(keyVaultName)" `
        "apiName=$(apiName)"
        

  - task: AzureCLI@2    
    displayName: "Set access to read Azure configurations"
    inputs:
      azureSubscription: "$(azureSubscription)"
      scriptType: "pscore"
      scriptLocation: "inlineScript"
      inlineScript: |        
        $azConfigDeployment = "azAppConfig"+"-"+"${{parameters.buildNumber}}"        
        $appConfigId=$(az deployment group show -g "$(rgName)" -n "$azConfigDeployment" --query properties.outputs.azConfigResourceId.value)
        $commonAppConfigId=$(az deployment group show -g "$(rgName)" -n "$azConfigDeployment" --query properties.outputs.azConfigCommonResourceId.value)
        
        $apiDeployment = "customersapi"+"-"+"${{parameters.buildNumber}}"
        
        $apiProductionId=$(az deployment group show -g "$(rgName)" -n "$apiDeployment" --query properties.outputs.productionApiPrincipalId.value)
        $apiStagingId=$(az deployment group show -g "$(rgName)" -n "$apiDeployment" --query properties.outputs.stagingApiPrincipalId.value)
        
        az role assignment create --role "App Configuration Data Reader" --assignee $apiProductionId --scope $appConfigId
        az role assignment create --role "App Configuration Data Reader" --assignee $apiStagingId --scope $appConfigId

        az role assignment create --role "App Configuration Data Reader" --assignee $apiProductionId --scope $commonAppConfigId
        az role assignment create --role "App Configuration Data Reader" --assignee $apiStagingId --scope $commonAppConfigId

  - task: AzureRmWebAppDeployment@3
    displayName: "Deploy to Staging"
    inputs:
      azureSubscription: "$(azureSubscription)"
      WebAppName: "cc-demo-customersapi-$(environmentName)"
      DeployToSlotFlag: true
      ResourceGroupName: "$(rgName)"
      SlotName: staging
      Package: "$(Pipeline.Workspace)/WebApp/Demo.AzureConfig.Customers.zip"
      ScriptType: "Inline Script"
      enableXmlVariableSubstitution: true

  - task: AzureAppServiceManage@0
    displayName: "Start Staging Slot"
    inputs:
      azureSubscription: "$(azureSubscription)"
      action: "Start Azure App Service"
      webAppName: "cc-demo-customersapi-$(environmentName)"
      specifySlotOrASE: true
      resourceGroupName: "$(rgName)"
      slot: staging

  - task: AzureAppServiceManage@0
    displayName: "Swap to Production"
    inputs:
      azureSubscription: "$(azureSubscription)"
      webAppName: "cc-demo-customersapi-$(environmentName)"
      resourceGroupName: "$(rgName)"
      sourceSlot: staging

  - task: AzureAppServiceManage@0
    displayName: "Stop Staging Slot"
    inputs:
      azureSubscription: "$(azureSubscription)"
      action: "Stop Azure App Service"
      webAppName: "cc-demo-customersapi-$(environmentName)"
      specifySlotOrASE: true
      resourceGroupName: "$(rgName)"
      slot: staging        